version: '3'
services:
    gym-duckietown-server:
        image: duckietown/gym-duckietown-server:2018.8.15
        networks:
        - gym-duckietown-net
        environment:
        - DISPLAY=:0
        - DUCKIETOWN_CHALLENGE=LF
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        ports:
        - "8902:8902"
        - "5558:5558"

    rosmaster:
        image: ros:kinetic-perception
        networks:
        - gym-duckietown-net
        ports:
        - "11311:11311"
        command: roscore